more faimond-ldap features: red error screen, [pxe]/fai_flags, [pxe]/nfs_opts, [pxe]/nfs_root and [pxe]/kern_appd read from server.conf (NOT faimond-ldap.conf!!)

diff --git a/main/generate_pxelinux_cfg b/main/generate_pxelinux_cfg
--- a/main/generate_pxelinux_cfg
+++ b/main/generate_pxelinux_cfg
@@ -29,9 +29,43 @@ echo "default fai-generated"
 echo
 echo "label fai-generated"
 
-case "$faistate" in
-  install*|error*) echo "kernel vmlinuz-install
-append  initrd=initrd.img-install nfsroot=/nfsroot,nfs4,union FAI_ACTION=install FAI_FLAGS=syslogd,verbose,sshd,poweroff ip=dhcp devfs=nomount root=/dev/nfs vga=788 dazuko=0 nomodeset watchdog=softdog,nowayout=1 panic=poweroff:120 quiet
+state=${faistate%%:*}
+error=${faistate#*:}
+kernel="$gotobootkernel"
+test -z "$kernel" -o "$kernel" = "default" && kernel="vmlinuz-install"
+initrd="initrd.img-${kernel#vmlinuz-}"
+
+conf="$(cat /etc/gosa-si/server.conf | tr '\t' ' ' | tr -s ' ' | sed 's/^ //;s/ $//;s/^\([^=]*\) =/\1=/;s/^\([^=]*\)= /\1=/')"
+
+echo "$conf" | grep -q "/$kernel=" 
+test $? != 0 -a "$state" != error && { 
+  state="error"
+  error="boot:666:ultra:The selected kernel $kernel is not available on the boot server"
+}
+  
+fai_flags=$(echo "$conf" | sed -n -r 's/^fai_flags=(.*)/\1/p' | tail -n 1)
+test -z "$fai_flags" && fai_flags="syslogd,verbose,sshd,poweroff"
+
+nfs_opts=$(echo "$conf" | sed -n -r 's/^nfs_opts=(.*)/\1/p' | tail -n 1)
+test -z "$nfs_opts" && nfs_opts="nfs4,union"
+
+nfs_root=$(echo "$conf" | sed -n -r 's/^nfs_root=(.*)/\1/p' | tail -n 1)
+test -z "$nfs_root" && nfs_root="/nfsroot"
+
+kern_appd=$(echo "$conf" | sed -n -r 's/^kern_appd=(.*)/\1/p' | tail -n 1)
+test -z "$kern_appd" && kern_appd="vga=788 dazuko=0 nomodeset watchdog=softdog,nowayout=1 panic=poweroff:120 quiet"
+
+case "$state" in
+  install*) echo "kernel $kernel
+append  initrd=$initrd nfsroot=${nfs_root},${nfs_opts} FAI_ACTION=install FAI_FLAGS=${fai_flags} ip=dhcp devfs=nomount root=/dev/nfs ${kern_appd}
+ipappend 2
+"
+  ;;
+  
+  error*) kernel="vmlinuz-install"    # make sure we load a kernel that can display the error
+          initrd="initrd.img-install"
+          echo "kernel $kernel
+append  initrd=$initrd nfsroot=${nfs_root},${nfs_opts} FAI_ACTION=sysinfo FAI_FLAGS=${fai_flags} FAI_ERROR=$(echo "$error" | base64 --wrap=0) ip=dhcp devfs=nomount root=/dev/nfs ${kern_appd}
 ipappend 2
 "
   ;;
